### PR TITLE
Look for Firefox in HKCU as well as HKLM (fix #73)

### LINKED ISSUE #73: Does not detect current Firefox from HKEY_CURRENT_USER
I came across this issue while investigating mozilla/web-ext#2201, and it seems to be the root cause.

Recent verisons of Firefox seem to install their registry keys in `HKEY_CURRENT_USER`. However node-fx-runner [only looks under `HKEY_LOCAL_MACHINE`](https://github.com/mozilla/node-fx-runner/blob/master/lib/utils.js#L87-L112), where in my case a much older version of Firefox (that does not exist) is referenced. This causes a file not found crash. I am not sure if Firefox *always* uses HKCU now or if it depends on the machine or installation process.

Output of `fx-runner start`: [error.txt](https://github.com/mozilla/node-fx-runner/files/6144945/error.txt)

## Keys under `HKEY_LOCAL_MACHINE`
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Mozilla Firefox]
@="55.0.3"
"CurrentVersion"="55.0.3 (x64 en-GB)"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Mozilla Firefox\55.0.3 (x64 en-GB)]
@="55.0.3 (x64 en-GB)"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Mozilla Firefox\55.0.3 (x64 en-GB)\Main]
"Install Directory"="C:\\Users\\Sam\\AppData\\Local\\Mozilla Firefox"
"PathToExe"="C:\\Users\\Sam\\AppData\\Local\\Mozilla Firefox\\firefox.exe"

[HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\Mozilla Firefox\55.0.3 (x64 en-GB)\Uninstall]
"Description"="Mozilla Firefox 55.0.3 (x64 en-GB)"
```
## Keys under `HKEY_CURRENT_USER`
```reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Mozilla\Mozilla Firefox]
@="86.0.1"
"CurrentVersion"="86.0.1 (x64 en-GB)"

[HKEY_CURRENT_USER\Software\Mozilla\Mozilla Firefox\86.0.1 (x64 en-GB)]
@="86.0.1 (x64 en-GB)"

[HKEY_CURRENT_USER\Software\Mozilla\Mozilla Firefox\86.0.1 (x64 en-GB)\Main]
"Install Directory"="E:\\Users\\Sam\\AppData\\Local\\Mozilla Firefox"
"PathToExe"="E:\\Users\\Sam\\AppData\\Local\\Mozilla Firefox\\firefox.exe"

[HKEY_CURRENT_USER\Software\Mozilla\Mozilla Firefox\86.0.1 (x64 en-GB)\Uninstall]
"Description"="Mozilla Firefox 86.0.1 (x64 en-GB)"
```
Although the values are very similar, notice the version difference between 86.0.1 and 55.0.3, which is 3 years older. My user folder is on the `E:\` drive so the old path no longer works.

### PR DESCRIPTION
**Pull request by mccreery**
Fix for #73. After revising my approach I'm fairly certain it works correctly. I extracted a couple of functions from `normalizeBinary` for getting the relevant registry values as promises and test in turn both registry hives before falling back on the standard program files path as before.

Tested by editing the registry to the following circumstances:
- Both keys in place, opens Firefox correctly
- Only HKLM key in place, old path found as before
- Both keys missing, falls back on program files as before

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -74,41 +74,41 @@ function normalizeBinary (binaryPath, platform, arch) {
...
-        }
-        resolve(key.value);
-      });
-    }, fallBack);
+// Returns a promise to get a single registry value
+function getRegistryValue(hive, key, name) {
+  return when.promise(function(resolve, reject) {
+    const registry = new Winreg({ hive, key });
+
+    registry.get(name, function(error, result) {
```
Comment (Rob--W) [inline lib/utils.js:105]: Rename`result` to `key`

**Review by Rob--W — COMMENTED** [review]
Implementation looks OK.

Could you add a unit test to verify the expected behavior in `test/run/utils.js` ?

File: lib/utils.js (hunk 1 above)
Comment (mccreery) [reply lib/utils.js:105]: Are you sure? There is a `key` in the enclosing scope and the library itself uses `result` since the key goes in and a value comes out.

**Comment by mccreery** [comment]
> Could you add a unit test to verify the expected behavior in `test/run/utils.js` ?
I'm not sure how to do this since I probably shouldn't be modifying registry keys for automated tests. Any ideas?

File: lib/utils.js (hunk 1 above)
Comment (Rob--W) [reply lib/utils.js:105]: Good point. Let's distinguish them by `parentKey` / `key` or `key` / `resultKey`.

**Comment by Rob--W** [comment]
> > Could you add a unit test to verify the expected behavior in `test/run/utils.js` ?
> 
> I'm not sure how to do this since I probably shouldn't be modifying registry keys for automated tests. Any ideas?

That test file mocks the `get` method of the `winreg` module, so that a dummy value is returned instead of the real keys.
You can find examples by searching for `.get = ` in `test/run/test.utils.js`. I encourage you to see multiple examples to get a better idea, but here is one slightly more complicated one: https://github.com/mozilla/node-fx-runner/blob/f1f0358073f74fbdf81caee2643ff2a9e7a25b99/test/run/test.utils.js#L163-L177

File: lib/utils.js (hunk 1 above)
Comment (mccreery) [reply lib/utils.js]: Sorted. I chose the latter to avoid the awkward `key: parentKey` on L103.

**Comment by mccreery** [comment]
I have added a new test for the expected behaviour and slightly modified the old registry test to ensure it checks the old behaviour is consistent.

File: test/run/test.utils.js [hunk 2]
```diff
@@ -35,14 +35,67 @@ describe("lib/utils", function () {
...
+    var winreg = function(options) {
+      this.get = function(_, fn) {
+        if (options.hive === winreg.HKLM) {
+          fn(null, {value: expected});
+        } else {
+          fn("Failed", null);
+        }
+      };
+    };
+    winreg.HKLM = 1;
```
Comment (Rob--W) [inline test/run/test.utils.js:51]: Let's use `"HKLM"` for consistency with the library at https://github.com/fresc81/node-winreg/blob/a24b16f3a7a403b82e88a07009b19e8ae7a40361/lib/registry.js#L17

SImilarly below.

File: test/run/test.utils.js [hunk 3]
```diff
@@ -35,14 +35,67 @@ describe("lib/utils", function () {
       return;
     }
 
-    // see ./mock-winreg.js
     var expected = "fake\\binary\\path";
+
+    // see ./mock-winreg.js
+    // Only mock keys in HKLM (local machine) hive
```
Comment (Rob--W) [inline test/run/test.utils.js:41]: I suppose that you changed the implementation to veify that the logic still works as intended when there is a HKLM-only registry key (i.e. without HKCU)? Can you clarify that intent in the comment, since it isn't obvious.

Comment (mccreery) [reply test/run/test.utils.js:41]: That's right. If you have all the correct keys in HKLM and some missing in HKCU the intended behaviour (as I see it) is to ignore HKCU and fall back on HKLM for all the keys.

Comment (Rob--W) [reply test/run/test.utils.js:41]: I meant in a code comment, not here :)

Comment (mccreery) [reply test/run/test.utils.js:41]: Haha, I thought it was a strange ask :P Will do.

**Comment by Rob--W** [comment]
Thanks for the patch and quick responses!
